export const PERMISSIONS = [
  'companies.view',
  'companies.create',
  'companies.update',
  'employees.view',
  'employees.create',
  'employees.update',
  'employees.delete',
  'employees.view_salary',
  'attendance.view',
  'attendance.create',
  'attendance.update',
  'attendance.approve',
  'leave.view',
  'leave.create',
  'leave.approve',
  'leave.reject',
  'payroll.view',
  'payroll.run',
  'payroll.approve',
  'payroll.export',
  'documents.view',
  'documents.upload',
  'documents.delete',
  'settings.view',
  'settings.update',
  'audit_logs.view',
] as const

export type Permission = (typeof PERMISSIONS)[number]
